import type { Finding, ScanResult, Severity, CryptoCategory } from "../types.js";
import { SEVERITY_ORDER } from "../types.js";

const VERSION = "0.2.0";

const SEVERITY_COLORS: Record<Severity, string> = {
  critical: "#dc2626",
  high: "#ea580c",
  medium: "#ca8a04",
  low: "#2563eb",
  safe: "#16a34a",
};

const SEVERITY_BG: Record<Severity, string> = {
  critical: "#fef2f2",
  high: "#fff7ed",
  medium: "#fefce8",
  low: "#eff6ff",
  safe: "#f0fdf4",
};

const CATEGORY_LABELS: Record<CryptoCategory, string> = {
  kem: "KEM",
  signature: "Signature",
  hash: "Hash",
  symmetric: "Symmetric",
  protocol: "Protocol",
  kdf: "KDF",
};

/**
 * Generate a self-contained HTML report for pqaudit scan results.
 * No external dependencies -- all CSS is inlined.
 */
export function formatHtml(result: ScanResult): string {
  const { summary } = result;
  const safeCount = summary.bySeverity.safe ?? 0;
  const totalFindings = summary.findingsTotal;
  const pqcScore =
    totalFindings > 0 ? Math.round((safeCount / totalFindings) * 100) : 100;

  const sortedFindings = [...result.findings].sort(
    (a, b) => SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity],
  );

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>pqaudit — Post-Quantum Readiness Report</title>
<style>
${css()}
</style>
</head>
<body>
<header class="header">
  <div class="container">
    <h1 class="header-title">pqaudit</h1>
    <p class="header-subtitle">Post-Quantum Readiness Report</p>
    <div class="header-meta">
      <span class="meta-item">Target: <code>${esc(result.target)}</code></span>
      <span class="meta-item">Scanned: ${esc(result.timestamp)}</span>
    </div>
    <div class="status-badge ${summary.pqcReady ? "status-ready" : "status-not-ready"}">
      ${summary.pqcReady ? "PQC READY" : "NOT PQC READY"}
    </div>
  </div>
</header>

<main class="container">
  ${renderDashboard(summary, pqcScore)}
  ${renderFindings(sortedFindings)}
</main>

<footer class="footer">
  <div class="container">
    <p>Generated by <a href="https://github.com/PQCWorld/pqaudit" rel="noopener noreferrer">pqaudit v${VERSION}</a></p>
    <p class="footer-timestamp">${esc(result.timestamp)}</p>
  </div>
</footer>
</body>
</html>`;
}

/* ---------- Section renderers ---------- */

function renderDashboard(
  summary: ScanResult["summary"],
  pqcScore: number,
): string {
  const severities: Severity[] = ["critical", "high", "medium", "low", "safe"];
  const categories = Object.keys(summary.byCategory) as CryptoCategory[];

  return `
<section class="dashboard">
  <h2 class="section-title">Summary</h2>
  <div class="dashboard-grid">
    <div class="card">
      <h3 class="card-title">Severity Breakdown</h3>
      <div class="badge-row">
${severities.map((s) => `        <span class="severity-badge" style="background:${SEVERITY_BG[s]};color:${SEVERITY_COLORS[s]};border:1px solid ${SEVERITY_COLORS[s]}20">${s}: ${summary.bySeverity[s]}</span>`).join("\n")}
      </div>
    </div>
    <div class="card">
      <h3 class="card-title">Category Breakdown</h3>
      <div class="badge-row">
${categories.map((c) => `        <span class="category-badge">${CATEGORY_LABELS[c] ?? c}: ${summary.byCategory[c]}</span>`).join("\n")}
      </div>
    </div>
    <div class="card stat-card">
      <div class="stat">
        <span class="stat-value">${summary.filesScanned}</span>
        <span class="stat-label">Files Scanned</span>
      </div>
      <div class="stat">
        <span class="stat-value">${summary.findingsTotal}</span>
        <span class="stat-label">Findings</span>
      </div>
      <div class="stat">
        <span class="stat-value" style="color:${pqcScore >= 80 ? "#16a34a" : pqcScore >= 50 ? "#ca8a04" : "#dc2626"}">${pqcScore}%</span>
        <span class="stat-label">PQC Score</span>
      </div>
    </div>
  </div>
</section>`;
}

function renderFindings(findings: Finding[]): string {
  if (findings.length === 0) {
    return `
<section class="findings">
  <h2 class="section-title">Findings</h2>
  <p class="no-findings">No findings detected. Your codebase appears post-quantum ready.</p>
</section>`;
  }

  return `
<section class="findings">
  <h2 class="section-title">Findings</h2>
  <div class="table-wrapper">
    <table class="findings-table">
      <thead>
        <tr>
          <th>Severity</th>
          <th>Algorithm</th>
          <th>Description</th>
          <th>File:Line</th>
          <th>Replacement</th>
          <th>Effort</th>
          <th>Confidence</th>
        </tr>
      </thead>
      <tbody>
${findings.map((f) => renderRow(f)).join("\n")}
      </tbody>
    </table>
  </div>
</section>`;
}

function renderRow(f: Finding): string {
  const loc = f.location.line
    ? `${f.location.file}:${f.location.line}`
    : f.location.file;
  const occ =
    f.occurrences && f.occurrences > 1
      ? ` <span class="occ-badge">${f.occurrences}x</span>`
      : "";
  const conf = `${Math.round(f.confidence * 100)}%`;

  return `        <tr class="severity-row-${f.severity}">
          <td><span class="severity-badge" style="background:${SEVERITY_BG[f.severity]};color:${SEVERITY_COLORS[f.severity]};border:1px solid ${SEVERITY_COLORS[f.severity]}20">${f.severity}</span></td>
          <td class="col-algo">${esc(f.algorithm)}${occ}</td>
          <td>${esc(f.description)}</td>
          <td class="col-file"><code>${esc(loc)}</code></td>
          <td>${f.replacement ? esc(f.replacement) : '<span class="na">--</span>'}</td>
          <td><span class="effort-badge effort-${f.effort}">${f.effort}</span></td>
          <td>${conf}</td>
        </tr>`;
}

/* ---------- CSS ---------- */

function css(): string {
  return `
:root {
  --bg: #ffffff;
  --fg: #1f2937;
  --fg-muted: #6b7280;
  --border: #e5e7eb;
  --header-bg: #111827;
  --header-fg: #f9fafb;
  --card-bg: #f9fafb;
  --table-stripe: #f9fafb;
  --badge-bg: #f3f4f6;
  --font-sans: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  --font-mono: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, Courier, monospace;
  --radius: 6px;
  --shadow: 0 1px 3px rgba(0,0,0,0.08);
}

*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

body {
  font-family: var(--font-sans);
  color: var(--fg);
  background: var(--bg);
  line-height: 1.6;
  -webkit-font-smoothing: antialiased;
}

.container { max-width: 1120px; margin: 0 auto; padding: 0 24px; }

/* --- Header --- */
.header {
  background: var(--header-bg);
  color: var(--header-fg);
  padding: 40px 0 32px;
}
.header-title {
  font-size: 28px;
  font-weight: 700;
  letter-spacing: -0.5px;
}
.header-subtitle {
  font-size: 15px;
  color: #9ca3af;
  margin-top: 2px;
}
.header-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 20px;
  margin-top: 16px;
  font-size: 13px;
  color: #9ca3af;
}
.header-meta code {
  font-family: var(--font-mono);
  background: rgba(255,255,255,0.08);
  padding: 1px 6px;
  border-radius: 3px;
  font-size: 12px;
}
.status-badge {
  display: inline-block;
  margin-top: 20px;
  padding: 6px 18px;
  font-size: 13px;
  font-weight: 700;
  letter-spacing: 0.5px;
  border-radius: 20px;
}
.status-ready {
  background: #064e3b;
  color: #6ee7b7;
  border: 1px solid #10b981;
}
.status-not-ready {
  background: #7f1d1d;
  color: #fca5a5;
  border: 1px solid #ef4444;
}

/* --- Dashboard --- */
.dashboard { margin-top: 32px; }
.section-title {
  font-size: 18px;
  font-weight: 600;
  margin-bottom: 16px;
  padding-bottom: 8px;
  border-bottom: 1px solid var(--border);
}
.dashboard-grid {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  gap: 16px;
}
.card {
  background: var(--card-bg);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 20px;
  box-shadow: var(--shadow);
}
.card-title {
  font-size: 13px;
  font-weight: 600;
  color: var(--fg-muted);
  text-transform: uppercase;
  letter-spacing: 0.3px;
  margin-bottom: 12px;
}
.badge-row {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
}
.severity-badge {
  display: inline-block;
  padding: 2px 10px;
  font-size: 12px;
  font-weight: 600;
  border-radius: 12px;
  white-space: nowrap;
}
.category-badge {
  display: inline-block;
  padding: 2px 10px;
  font-size: 12px;
  font-weight: 500;
  border-radius: 12px;
  background: var(--badge-bg);
  color: var(--fg);
  border: 1px solid var(--border);
}
.stat-card {
  display: flex;
  align-items: center;
  justify-content: space-around;
}
.stat { text-align: center; }
.stat-value {
  display: block;
  font-size: 28px;
  font-weight: 700;
  line-height: 1.2;
}
.stat-label {
  display: block;
  font-size: 11px;
  color: var(--fg-muted);
  text-transform: uppercase;
  letter-spacing: 0.3px;
  margin-top: 2px;
}

/* --- Findings Table --- */
.findings { margin-top: 32px; }
.table-wrapper { overflow-x: auto; }
.findings-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 13px;
}
.findings-table th {
  text-align: left;
  padding: 10px 12px;
  font-size: 11px;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.3px;
  color: var(--fg-muted);
  border-bottom: 2px solid var(--border);
  white-space: nowrap;
}
.findings-table td {
  padding: 10px 12px;
  border-bottom: 1px solid var(--border);
  vertical-align: top;
}
.findings-table tbody tr:nth-child(even) { background: var(--table-stripe); }
.findings-table tbody tr:hover { background: #eef2ff; }
.col-file code {
  font-family: var(--font-mono);
  font-size: 12px;
  background: var(--badge-bg);
  padding: 1px 5px;
  border-radius: 3px;
  word-break: break-all;
}
.col-algo { font-weight: 600; white-space: nowrap; }
.occ-badge {
  display: inline-block;
  margin-left: 4px;
  padding: 0 5px;
  font-size: 10px;
  font-weight: 600;
  background: var(--badge-bg);
  color: var(--fg-muted);
  border-radius: 8px;
  border: 1px solid var(--border);
}
.effort-badge {
  display: inline-block;
  padding: 1px 8px;
  font-size: 11px;
  font-weight: 500;
  border-radius: 10px;
  white-space: nowrap;
}
.effort-trivial { background: #f0fdf4; color: #16a34a; }
.effort-moderate { background: #fefce8; color: #ca8a04; }
.effort-complex { background: #fff7ed; color: #ea580c; }
.effort-breaking { background: #fef2f2; color: #dc2626; }
.na { color: var(--fg-muted); }
.no-findings {
  padding: 40px;
  text-align: center;
  color: var(--fg-muted);
  font-size: 15px;
}

/* --- Footer --- */
.footer {
  margin-top: 48px;
  padding: 24px 0;
  border-top: 1px solid var(--border);
  font-size: 12px;
  color: var(--fg-muted);
  text-align: center;
}
.footer a {
  color: #2563eb;
  text-decoration: none;
}
.footer a:hover { text-decoration: underline; }
.footer-timestamp { margin-top: 4px; }

/* --- Responsive --- */
@media (max-width: 768px) {
  .dashboard-grid { grid-template-columns: 1fr; }
  .header-meta { flex-direction: column; gap: 4px; }
  .stat-card { flex-direction: column; gap: 16px; }
  .findings-table { font-size: 12px; }
  .findings-table th, .findings-table td { padding: 8px 6px; }
}
`;
}

/* ---------- Utilities ---------- */

function esc(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
